# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Martin Pecka's blog
email: peci1@seznam.cz
description: > # this means to ignore newlines until "baseurl:"
  What interested me during volunteer and research programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://peci1.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  peci1

# Build settings
markdown: kramdown
